# Generated by Django 2.2.16 on 2021-05-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210521_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_nuber',
            field=models.CharField(default='XXXXXXXXXX', max_length=10),
        ),
    ]
