# Generated by Django 2.2.16 on 2021-05-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisebuy',
            name='negotiable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='advertisebuy',
            name='price',
            field=models.CharField(default='XXXX', max_length=10),
        ),
        migrations.AddField(
            model_name='advertisesell',
            name='negotiable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='advertisesell',
            name='price',
            field=models.CharField(default='XXXX', max_length=10),
        ),
    ]
