# Generated by Django 2.2.16 on 2021-05-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210524_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisesell',
            name='product_image',
            field=models.ImageField(default='default_profile.png', upload_to='product_images'),
        ),
    ]
