# Generated by Django 2.2.16 on 2021-05-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210525_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisesell',
            name='product_image',
            field=models.ImageField(default='default_prod.jpeg', upload_to='product_images'),
        ),
    ]
